$(function(){
    $("#draggable1").draggable();
    $("#draggable2").draggable();
    $("#draggable3").draggable();
    $("#draggable4").draggable();
    $("#draggable5").draggable();
    $("#draggable6").draggable();
    $("#draggable7").draggable();
    $("#draggable8").draggable();
    $("#draggable9").draggable();
    $("#draggable10").draggable();
});
